### ISSUE TITLE
How can I get statistics on the package outside of top 100?

### ISSUE THREAD

**Issue by drom** [cdnjs/cf-stats#6]

**Comment by MattIPv4** [comment]
We have no automatic process for this as we do not have access to full logs or stats from Cloudflare. If you have a specific package that you'd like more information on though, I may be able to ask Cloudflare to pull that data up for you.

**Comment by drom** [comment]
Yes, that would be nice. The name of the package is: `wavedrom`

**Comment by MattIPv4** [comment]
What stats would you like for that package?

**Comment by drom** [comment]
unique users, per month, per version?
total downloads per month, per version?
per day, per week?
as detail as possible. I can filter

**Comment by acao** [comment]
would like to know the same about `graphiql` package if possible? it would be cool if you could configure reportig for this from your cloudflare dashboard some day... :D

**Comment by MattIPv4** [comment]
We don't have access to the Cloudflare dashboard, as the `cdnjs.cloudflare.com` subdomain is part of the main `cloudflare.com` dashboard.

I have not yet had time to reach out to Cf to request stats for the original request, and I do not wish for this issue to become a vector for people attempting to get stats for their libraries. We do not have a maintainable way to offer stats, nor do we have access to fetch them so this puts a workload of the Cf support staff.

As such, I'm going to close this issue, sorry.
